### ISSUE TITLE
Calyptos: Installation errors for 4.2 VPC deployment

### ISSUE THREAD

**Issue by dmccue** [eucalyptus/calyptos#55]
# [ufs]
# odc-f-25.prc.eucalyptus-systems.com: 10.104.10.67
# [clc]
# odc-f-09.prc.eucalyptus-systems.com: 10.104.10.51
# [walrus]
# odc-f-02.prc.eucalyptus-systems.com: 10.104.10.44
# [cc]
# odc-f-28.prc.eucalyptus-systems.com: 10.104.10.70
# [sc]
# odc-f-28.prc.eucalyptus-systems.com: 10.104.10.70
# [nc]
# odc-f-31.prc.eucalyptus-systems.com: 10.104.10.73
# odc-f-36.prc.eucalyptus-systems.com: 10.104.10.78
# odc-d-30.prc.eucalyptus-systems.com: 10.104.1.209

Using master branch of calyptos as of 1/Sep/15

1) Servers are reset using cobbler to defaults then wait until port 22 is present
2) ssh-keygen -R <ip> used on all ip addresses to clear known hosts
3) calyptos validate -e environment.yml | tee validate.log
Successful (logs attached)
4) calyptos prepare -e environment.yml | tee prepare.log
Successful (logs attached)
5) calyptos bootstrap -e environment.yml | tee bootstrap.log
Successful (logs attached)

We're left with the following configuration:

```
[root@odc-f-09 ~]# euca-describe-services
SERVICE user-api            API_10.104.10.51    API_10.104.10.51        ENABLED     29  http://10.104.10.51:8773/services/User-API  arn:euca:bootstrap:API_10.104.10.51:user-api:API_10.104.10.51/
SERVICE autoscaling         API_10.104.10.51    API_10.104.10.51.autoscaling    ENABLED     29      http://10.104.10.51:8773/services/AutoScaling   arn:euca:bootstrap:API_10.104.10.51:autoscaling:API_10.104.10.51.autoscaling/
SERVICE cloudformation      API_10.104.10.51    API_10.104.10.51.cloudformation ENABLED     29      http://10.104.10.51:8773/services/CloudFormation    arn:euca:bootstrap:API_10.104.10.51:cloudformation:API_10.104.10.51.cloudformation/
SERVICE cloudwatch          API_10.104.10.51    API_10.104.10.51.cloudwatch ENABLED     29      http://10.104.10.51:8773/services/CloudWatch    arn:euca:bootstrap:API_10.104.10.51:cloudwatch:API_10.104.10.51.cloudwatch/
SERVICE compute             API_10.104.10.51    API_10.104.10.51.compute    ENABLED     29      http://10.104.10.51:8773/services/compute   arn:euca:bootstrap:API_10.104.10.51:compute:API_10.104.10.51.compute/
    SERVICEACCOUNT  (eucalyptus)aws-exec-read               000702698367    23e5f633f364a34192a4b492433548e4b20222e26464919115c355b28223b5e1
SERVICE dns                 API_10.104.10.51    API_10.104.10.51.dns    ENABLED     29  http://10.104.10.51:8773/services/Dns   arn:euca:bootstrap:API_10.104.10.51:dns:API_10.104.10.51.dns/
SERVICE euare               API_10.104.10.51    API_10.104.10.51.euare  ENABLED     29  http://10.104.10.51:8773/services/Euare arn:euca:bootstrap:API_10.104.10.51:euare:API_10.104.10.51.euare/
SERVICE identity            API_10.104.10.51    API_10.104.10.51.identity   ENABLED     29      http://10.104.10.51:8773/services/Identity  arn:euca:bootstrap:API_10.104.10.51:identity:API_10.104.10.51.identity/
SERVICE imaging             API_10.104.10.51    API_10.104.10.51.imaging    ENABLED     29      http://10.104.10.51:8773/services/Imaging   arn:euca:bootstrap:API_10.104.10.51:imaging:API_10.104.10.51.imaging/
SERVICE loadbalancing       API_10.104.10.51    API_10.104.10.51.loadbalancing  ENABLED     29      http://10.104.10.51:8773/services/LoadBalancing arn:euca:bootstrap:API_10.104.10.51:loadbalancing:API_10.104.10.51.loadbalancing/
    SERVICEACCOUNT  (eucalyptus)loadbalancing               000424115143    2cabf3b18161310322e2365e3a5b817214e53733584b471f255e293a325c5858
SERVICE objectstorage       API_10.104.10.51    API_10.104.10.51.objectstorage  BROKEN      29      http://10.104.10.51:8773/services/objectstorage arn:euca:bootstrap:API_10.104.10.51:objectstorage:API_10.104.10.51.objectstorage/
SERVICE simpleworkflow      API_10.104.10.51    API_10.104.10.51.simpleworkflow ENABLED     29      http://10.104.10.51:8773/services/SimpleWorkflow    arn:euca:bootstrap:API_10.104.10.51:simpleworkflow:API_10.104.10.51.simpleworkflow/
SERVICE tokens              API_10.104.10.51    API_10.104.10.51.tokens ENABLED     29  http://10.104.10.51:8773/services/Tokens    arn:euca:bootstrap:API_10.104.10.51:tokens:API_10.104.10.51.tokens/
SERVICE reporting           bootstrap   10.104.10.51            ENABLED     29      http://10.104.10.51:8773/services/Reporting arn:euca:bootstrap::reporting:10.104.10.51/
SERVICE bootstrap           bootstrap   10.104.10.51            ENABLED     29      http://10.104.10.51:8773/services/Empyrean  arn:euca:bootstrap:::10.104.10.51/ 
SERVICE pollednotifications eucalyptus  10.104.10.51            ENABLED     29      http://10.104.10.51:8773/services/PolledNotifications   arn:euca:eucalyptus::pollednotifications:10.104.10.51/
SERVICE imagingbackend      eucalyptus  10.104.10.51            NOTREADY    29      http://10.104.10.51:8773/services/ImagingBackend    arn:euca:eucalyptus::imagingbackend:10.104.10.51/
SERVICE jetty               eucalyptus  10.104.10.51            ENABLED     29      http://10.104.10.51:8773/services/Jetty arn:euca:eucalyptus::jetty:10.104.10.51/
SERVICE loadbalancingbackend    eucalyptus  10.104.10.51            NOTREADY    29      http://10.104.10.51:8773/services/LoadBalancingBackend  arn:euca:eucalyptus::loadbalancingbackend:10.104.10.51/
SERVICE notifications       eucalyptus  10.104.10.51            ENABLED     29      http://10.104.10.51:8773/services/Notifications arn:euca:eucalyptus::notifications:10.104.10.51/
SERVICE autoscalingbackend  eucalyptus  10.104.10.51            ENABLED     29      http://10.104.10.51:8773/services/AutoScalingBackend    arn:euca:eucalyptus::autoscalingbackend:10.104.10.51/
SERVICE cloudwatchbackend   eucalyptus  10.104.10.51            ENABLED     29      http://10.104.10.51:8773/services/CloudWatchBackend arn:euca:eucalyptus::cloudwatchbackend:10.104.10.51/
SERVICE eucalyptus          eucalyptus  10.104.10.51            ENABLED     29      http://10.104.10.51:8773/services/Eucalyptus    arn:euca:eucalyptus:::10.104.10.51/
SERVICE cluster             one         one-cc-1                NOTREADY    29      http://10.104.10.70:8774/axis2/services/EucalyptusCC    arn:euca:eucalyptus:one:cluster:one-cc-1/
SERVICE storage             one         one-sc-1                BROKEN      29      http://10.104.10.70:8773/services/Storage   arn:euca:eucalyptus:one:storage:one-sc-1/
SERVICE walrusbackend       walrus      walrus-1                BROKEN      29      http://10.104.10.44:8773/services/WalrusBackend arn:euca:bootstrap:walrus:walrusbackend:walrus-1/
```

Problems:
- Cluster controller hasn't been setup
- Storage controller hasn't been setup
- Walrus hasn't been setup
- eucarc hasn't been re-downloaded after registration
- loadbalancer / imageworker hasn't been setup
- default image specified at default-img-url: http://images.walrus.cloud.qa1.eucalyptus-systems.com:8773/precise-server-cloudimg-amd64-disk1.img hasn't been installed
- euca-describe-vpcs/euca-describe-vpc-peering-connections etc is empty
- empyrean-describe-services: error: No empyrean endpoint to connect to was given
- no ability to specify ufs server other than via *id001 (clc)

Feel free to access on ssh root@10.104.10.51 for verification

**Comment by dmccue** [comment]
All logs and yml file attached in https://eucalyptus.atlassian.net/wiki/download/attachments/89128972/calyptos-midokura.tgz?api=v2

**Comment by viglesiasce** [comment]
Thanks @dmccue 

On first look it appears that after bootstrap the necessary artifacts (node jsons) werent pulled back from the CLC. Need to figure out why. Im on 10.104.10.51 now and trying to reproduce.

**Comment by viglesiasce** [comment]
I think I figured out the cascade of issues here each one is either a validator or error handling bug:
- Prepare did not install chef-client on a machine that was in the midolman hostmapping but no where else (validator)
  - That caused bootstrap to bail very early on before the error messaging even picked up the failure (EH)
  - Provision was started but the CLC hadnt been bootstrapped and keys werent able to be synced (EH)

**Comment by viglesiasce** [comment]
I opened the following:

https://github.com/eucalyptus/calyptos/issues/56
https://github.com/eucalyptus/calyptos/issues/57
https://github.com/eucalyptus/calyptos/issues/58

**Comment by dmccue** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/calyptos", line 4, in <module>
    __import__('pkg_resources').run_script('calyptos===fec8a15', 'calyptos')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/calyptos-fec8a15-py2.7.egg/EGG-INFO/scripts/calyptos", line 281, in <module>

  File "/usr/local/lib/python2.7/site-packages/calyptos-fec8a15-py2.7.egg/EGG-INFO/scripts/calyptos", line 120, in provision

  File "/usr/local/lib/python2.7/site-packages/calyptos-fec8a15-py2.7.egg/EGG-INFO/scripts/calyptos", line 85, in run_driver

  File "build/bdist.macosx-10.10-x86_64/egg/calyptos/plugins/deployer/chef.py", line 141, in provision
  File "build/bdist.macosx-10.10-x86_64/egg/calyptos/chefmanager.py", line 146, in add_to_run_list
  File "build/bdist.macosx-10.10-x86_64/egg/calyptos/chefmanager.py", line 129, in get_node_name_by_ip
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

https://eucalyptus.atlassian.net/secure/attachment/25611/calyptos-1441138161.tgz

After the calyptos additions we're getting the above stacktrace, all files attached in tgz file.

**Comment by viglesiasce** [comment]
I figured out this last bit and added better error handling here: f998a0a443a45741445aeeebaaa669973dc95a8b

I had to add the EucanetdHost to the midolman hostmapping. 

Here is the full env i used. Things are up now but you hit [this bug](https://eucalyptus.atlassian.net/browse/EUCA-11327) which is stopping the loadbalancing service from starting but is not related to calyptos.

```
---
#Original source
#https://eucalyptus.atlassian.net/wiki/download/attachments/78905500/environment.yml?version=1&modificationDate=1440021213860&api=v2

#[ufs]??????
#odc-f-25.prc.eucalyptus-systems.com ansible_ssh_host=10.104.10.67
#[clc]
#odc-f-09.prc.eucalyptus-systems.com ansible_ssh_host=10.104.10.51
#[walrus]
#odc-f-02.prc.eucalyptus-systems.com ansible_ssh_host=10.104.10.44
#[cc]
#odc-f-28.prc.eucalyptus-systems.com ansible_ssh_host=10.104.10.70
#[sc]
#odc-f-28.prc.eucalyptus-systems.com ansible_ssh_host=10.104.10.70
#[nc]
#odc-f-31.prc.eucalyptus-systems.com ansible_ssh_host=10.104.10.73
#odc-f-36.prc.eucalyptus-systems.com ansible_ssh_host=10.104.10.78
#odc-d-30.prc.eucalyptus-systems.com ansible_ssh_host=10.104.1.209


default_attributes:
  eucalyptus:
    default-img-url: http://images.walrus.cloud.qa1.eucalyptus-systems.com:8773/precise-server-cloudimg-amd64-disk1.img
    enterprise-repo: http://packages.release.eucalyptus-systems.com/yum/tags/enterprise-devel/centos/6/x86_64/
    euca2ools-repo: http://packages.release.eucalyptus-systems.com/yum/tags/euca2ools-devel/centos/6/x86_64/
    eucalyptus-repo: http://packages.release.eucalyptus-systems.com/yum/tags/eucalyptus-devel/centos/6/x86_64/
    init-script-url: http://git.qa1.eucalyptus-systems.com/qa-repos/eucalele/raw/master/deploy-helpers/scripts/network-interfaces.sh
    install-imaging-worker: 'true'
    install-load-balancer: 'true'
    install-type: packages
    log-level: DEBUG
    nc:
      max-cores: 32
    network:
      bridge-interface: br0
      bridged-nic: em1
      config-json:
        InstanceDnsServers:
        - 10.104.10.51
        Mido:
          EucanetdHost: odc-f-28.prc.eucalyptus-systems.com
          GatewayHost: odc-f-28.prc.eucalyptus-systems.com
          GatewayIP: 10.105.10.70
          GatewayInterface: em1
          PublicGatewayIP: 10.104.10.70
          PublicNetworkCidr: 10.104.0.0/16
        Mode: VPCMIDO
        PublicIps:
        - 10.116.156.0-10.116.156.254
      mode: VPCMIDO
      private-interface: br0
      public-interface: br0
    post-script-url: http://git.qa1.eucalyptus-systems.com/qa-repos/eucalele/raw/master/deploy-helpers/scripts/midonet_post.sh
    source-branch: VPC-SHARED-SETUP
    source-repo: ssh://repo-euca@git.eucalyptus-systems.com/internal
    system-properties:
      cloudformation.url_domain_whitelist: '*s3.amazonaws.com, git.qa1.eucalyptus-systems.com'
      services.imaging.worker.instance_type: m1.medium
    topology:
      clc-1: 10.104.10.51
      clusters:
        one:
          cc-1: 10.104.10.70
          das-device: vg01
          nodes: 10.104.10.73 10.104.10.78 10.104.1.209
          sc-1: 10.104.10.70
          storage-backend: das
      user-facing:
      - 10.104.10.51
      walrus: 10.104.10.44
    yum-options: --nogpg
  midokura:
    #bgp-peers:
    #- local-as: 64941
    #  peer-address: 10.116.133.173
    #  port-ip: 10.116.129.174
    #  remote-as: 65000
    #  route: 10.116.156.0/24
    #  router-name: eucart
    cassandras:
    - 10.104.10.70
    initial-tenant: euca_tenant_1
    midolman-host-mapping:
      odc-f-28.prc.eucalyptus-systems.com: 10.104.10.70
      odc-f-09.prc.eucalyptus-systems.com: 10.104.10.51
      odc-f-31.prc.eucalyptus-systems.com: 10.104.10.73
      odc-f-36.prc.eucalyptus-systems.com: 10.104.10.78
      odc-d-30.prc.eucalyptus-systems.com: 10.104.1.209
    midonet-api-url: http://10.104.10.70:8080/midonet-api
    repo-password: 8yU8Pj6h
    repo-url: http://mirror.eucalyptus-systems.com/mirrors/midokura-rc/
    repo-username: eucalyptus
    yum-options: --nogpg
    zookeepers:
    - 10.104.10.70:2181
description: Eucalyptus MIDOVPC Testing - DSM
name: dsm-001
```

**Comment by dmccue** [comment]
Thanks Vic, i'll test this out shortly and report back.

**Comment by dmccue** [comment]
Hi Vic, I think we're close to getting it installed for the first time.
There was an error this time with the NC install on IP 10.104.1.209 (calyptos-failure-10.104.1.209.log in tgz) due to 10.107.101.209 already being occupied and br0 not being created

using calyptos: f998a0a
environment.yml attached in tgz

``` bash
Running handlers:
[2015-09-03T07:31:45-07:00] ERROR: Running exception handlers
Running handlers complete
[2015-09-03T07:31:45-07:00] ERROR: Exception handlers complete
[2015-09-03T07:31:45-07:00] FATAL: Stacktrace dumped to /root/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 30 resources updated in 141.140049383 seconds
[2015-09-03T07:31:45-07:00] ERROR: execute[network-restart] (eucalyptus::node-controller line 88) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of service network restart ----
STDOUT: Shutting down interface em1.107:  [  OK  ]
Shutting down interface em1.116:  [  OK  ]
Shutting down interface em1:  [  OK  ]
Shutting down interface em2:  [  OK  ]
Shutting down loopback interface:  [  OK  ]
Bringing up loopback interface:  [  OK  ]
Bringing up interface em1:  [  OK  ]
Bringing up interface em2:  Determining if ip address 10.105.1.209 is already in use for device em2...
[  OK  ]
Bringing up interface em1.107:  Determining if ip address 10.107.101.209 is already in use for device em1.107...
Error, some other host already uses address 10.107.101.209.
[FAILED]
Bringing up interface em1.116:  [  OK  ]
Bringing up interface br0:  
Determining IP information for br0... done.
[  OK  ]
STDERR: bridge br0 does not exist!
---- End output of service network restart ----
Ran service network restart returned 1
[2015-09-03T07:31:45-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

https://eucalyptus.atlassian.net/secure/attachment/25619/calyptos-1441290844.tgz

This is what we have after install:
[clc]
source eucarc
mkdir -p creds/admin && cd $_ && euca_conf --get-credentials=admin.zip && unzip admin.zip && source eucarc

``````
[root@odc-f-09 admin]# empyrean-describe-services --region @localhost
SERVICE  autoscaling           API_10.104.10.67  API_10.104.10.67.autoscaling     enabled                                                                                                            
SERVICE  autoscalingbackend    eucalyptus        10.104.10.51                     enabled                                                                                                            
SERVICE  bootstrap             bootstrap         10.104.10.51                     enabled                                                                                                            
SERVICE  cloudformation        API_10.104.10.67  API_10.104.10.67.cloudformation  enabled                                                                                                            
SERVICE  cloudwatch            API_10.104.10.67  API_10.104.10.67.cloudwatch      enabled                                                                                                            
SERVICE  cloudwatchbackend     eucalyptus        10.104.10.51                     enabled                                                                                                            
SERVICE  cluster               one               one-cc-1                         enabled                                                                                                            
SERVICE  compute               API_10.104.10.67  API_10.104.10.67.compute         enabled   (eucalyptus)aws-exec-read:000301006772:5311a6322f1751595745614624f6150613e2e5c542f3d493a34451d1b20411ca  
SERVICE  dns                   API_10.104.10.67  API_10.104.10.67.dns             enabled                                                                                                            
SERVICE  euare                 API_10.104.10.67  API_10.104.10.67.euare           enabled                                                                                                            
SERVICE  eucalyptus            eucalyptus        10.104.10.51                     enabled                                                                                                            
SERVICE  identity              API_10.104.10.67  API_10.104.10.67.identity        enabled                                                                                                            
SERVICE  imaging               API_10.104.10.67  API_10.104.10.67.imaging         enabled                                                                                                            
SERVICE  imagingbackend        eucalyptus        10.104.10.51                     notready                                                                                                           
SERVICE  jetty                 eucalyptus        10.104.10.51                     enabled                                                                                                            
SERVICE  loadbalancing         API_10.104.10.67  API_10.104.10.67.loadbalancing   enabled   (eucalyptus)loadbalancing:000215252614:3926401e2e2265f3654501320474b1110252ea1b22c473c571415423026531f3  
SERVICE  loadbalancingbackend  eucalyptus        10.104.10.51                     notready                                                                                                           
SERVICE  notifications         eucalyptus        10.104.10.51                     enabled                                                                                                            
SERVICE  objectstorage         API_10.104.10.67  API_10.104.10.67.objectstorage   broken                                                                                                             
SERVICE  pollednotifications   eucalyptus        10.104.10.51                     enabled                                                                                                            
SERVICE  reporting             bootstrap         10.104.10.51                     enabled                                                                                                            
SERVICE  simpleworkflow        API_10.104.10.67  API_10.104.10.67.simpleworkflow  enabled                                                                                                            
SERVICE  storage               one               one-sc-1                         broken                                                                                                             
SERVICE  tokens                API_10.104.10.67  API_10.104.10.67.tokens          enabled                                                                                                            
SERVICE  user-api              API_10.104.10.67  API_10.104.10.67                 enabled                                                                                                            
SERVICE  walrusbackend         walrus            walrus-1                         enabled     ```

Remaining issues:
~~ Getting 504 errors on the eucaconsole after login - Fixed ~~
~~ EUCA-11329 - Loadbalancer install has unexpected behavior ~~
~~ EUCA-11330 - Imaging worker install has unexpected behavior ~~
~~ 10.104.1.209 wasn't added to node array due to broken network-scripts interface config ~~
``````

**Comment by dmccue** [comment]
euca-run-instances is throwing back errors related to InstanceType but it's actually because of VPC networking not being initialized.

euca-create-vpc 192.168.0.0/16
euca-create-subnet -c vpc-e010355e -i 192.168.1.0/24
euca-describe-groups
euca-authorize -P tcp -p 22 -s 0.0.0.0/0 sg-4939ac7b
euca-run-instances -k admin -t m1.large -s subnet-ac586ec2 -g sg-4939ac7b emi-f27db42a
euca-run-instances: error (RunInstancesType): RunInstancesType

Would you have any documentation on what cloud.network.network_configuration should be set to?

**Comment by viglesiasce** [comment]
@dmccue 

If a piece of the provision step fails it does not continue on to finish the rest of the install. Thats why you'll see things partially configured.

**Comment by dmccue** [comment]
All services now showing green! Also the default vpc and subnet has been created!
When I create instances however they halt at pending:

``` bash
[root@odc-f-09 ~]# euca-describe-instances
RESERVATION r-e5c9669c  000273883112    default
INSTANCE    i-cee93502  emi-d68180a0    10.116.156.1    172.31.15.181   pending admin   0   m1.medium   2015-09-03T19:27:46.121Z    az-01               monitoring-disabled 10.116.156.1    172.31.15.181   vpc-5f3c3de0    subnet-6faf2421 instance-store              hvm         sg-2a0ff50f             x86_64
NETWORKINTERFACE    eni-0c1b935a    subnet-6faf2421 vpc-5f3c3de0    000273883112    in-use  172.31.15.181   euca-172-31-15-181.eucalyptus.internal  true
ATTACHMENT      0   attached    2015-09-03T19:27:46.124Z    true
ASSOCIATION 10.116.156.1        172.31.15.181
PRIVATEIPADDRESS    172.31.15.181   euca-172-31-15-181.eucalyptus.internal  primary
TAG instance    i-cee93502  euca:node   10.104.10.78
```

https://eucalyptus.atlassian.net/secure/attachment/25621/calyptos-1441302819.tgz

Likely to be related to missing VPC static routes, could this be added as a feature if default-attributes:eucalyptus:midokura:bgp-peers isn't specified or set to false?
Also we're going to have to figure out how to register components using the private ip addresses of the servers rather than public .. 10.104.10.x = public, 10.105.10.x = private

**Comment by viglesiasce** [comment]
Static routes are a property of the external network that we don't control as part of our install. Do you have a proposal for what you would want in that case? Namely we would need access to the core router or all boxes that would be used as clients.

Bind address setting was added recently. You would set the following:

```
default_attributes:
    eucalyptus:
         set-bind-addr: true
         bind-interface: bond0.2001 # this is the interface that you want to bind Euca to
```

Additionally in the topology you would use the IPs of the registration network.
